[package]
name = "thirtyfour_webdriver_console"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
env = "0.0.0"
env_logger = "0.11.3"
fmt = "0.1.0"
log = "0.4.22"
stdext = "0.3.3"
thirtyfour = "0.32.0"
tokio = { version = "1.38.0", features = ["full"] }
